### ISSUE TITLE
There is no zero or "oh" for 8:02 etc

### ISSUE THREAD

**Issue by BeJay8675309** [paulseward/asterisk-tim#2]
This is a great project and it works really well, the only thing that seems missing is digits that are 0-9 don't have a zero prefix or an "oh" sound. It says "eight two" instead of "eight oh two" or "eight zero two". Is this a bug or a feature? It would be a great addition if it's not a bug. Thanks

**Comment by paulseward** [comment]
Hi!  Thanks for the interest.  These recordings are taken from actual, physical, speaking clock machines made by the British Post Office, and those machines didn't announce the time as "eight oh two" - they announced as "eight two" 

The aim of this project was to recreate those machines as faithfully as possible, so I guess you'd describe this as a feature!

Although Pat Simmons and Gordon Gow are both long dead (so not available to make a new recordings!) you could probably crop the "oh" from "o'clock" and add the feature yourself, however, I wouldn't accept a pull request for it, as it wouldn't be faithful to the original machines.

I think speaking clocks in the USA might have the phrasing you're looking for, try searching the internet for "Jane Barbe" recordings.

**Comment by BeJay8675309** [comment]
Thanks for the follow up Paul, I have used of our Australian one with this "oh" feature, but it is obviously more recent with Richard Peach, not Gordon Gow :)

**Comment by BeJay8675309** [comment]
Thanks for the follow up Paul.

**Comment by paulseward** [comment]
@BeJay8675309 The Gordon Gow recordings here have another "fault" which is a quirk of the machine they were recorded from (which was the prototype for the ones built for australia).  The optical disk for the minutes is mounted slightly off-centre, and you get bleed-through from the adjacent audio track.  This is most noticeable on the "nine" recording.  Again, this was a fault with the prototype, so I've left it in :)

**Comment by BeJay8675309** [comment]
Love the attention to detail :) Thanks again for the quality, and now understandably period correct effort you have done with this! I have this running on a Rpi with Asterisk and a Linksys SPA with SO<ext> prefix to auto dial the macro. Now my 202 (AUS) series Bakelite phone tells the time. Cheers
